# Generated by Django 5.0 on 2025-03-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
