# Generated by Django 5.1.6 on 2025-02-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_journal_options_alter_journal_language_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journal",
            options={},
        ),
        migrations.RenameField(
            model_name="journal",
            old_name="created_at",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="journal",
            old_name="updated_at",
            new_name="edit_date",
        ),
        migrations.AddField(
            model_name="journal",
            name="title",
            field=models.CharField(default="Untitled Journal", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="journal",
            name="language",
            field=models.CharField(default="en", max_length=20),
        ),
    ]
