# Generated by Django 5.1.6 on 2025-02-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "journal",
            "0003_alter_journal_options_rename_created_at_journal_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="journal",
            old_name="content",
            new_name="encrypted_content",
        ),
    ]
