# Generated by Django 5.1.6 on 2025-02-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_rename_content_journal_encrypted_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="journal",
            old_name="encrypted_content",
            new_name="content",
        ),
    ]
