# Generated by Django 5.1.7 on 2025-04-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Regular User'), ('ADMIN', 'Administrator'), ('SUPERADMIN', 'Super Administrator')], default='USER', max_length=20),
        ),
    ]
