# Generated by Django 5.1.7 on 2025-04-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='NPR', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Credit/Debit Card'), ('PAYPAL', 'PayPal'), ('BANK', 'Bank Transfer'), ('ESEWA', 'eSewa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscription.subscription'),
        ),
    ]
