# Generated by Django 5.0 on 2025-03-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direct_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="direct_chat.conversation",
            ),
        ),
    ]
